server:
  port: 8888


spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:azo-db.cu1ht1d9andz.ap-south-1.rds.amazonaws.com}:3306/azoDB
    username: root
    password: Passowrd#2024
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

###########APP Config#####################

security:
  jwt:
    token:
       secret-key: my-secret-key
logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    org.springframework.security.jackson2: INFO